#!/bin/sh -e

mkdir -p build
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_RSVG:BOOL=OFF \
    -DENABLE_SN:BOOL=OFF ..

make
make DESTDIR="$1" install
